### GET All Foos
GET http://localhost:8080/foos?offset=0&limit=10
Accept: application/json

> {%
    if (response.status !== 200) {
        throw new Error(`Expected status 200 but got ${response.status}`);
    }
%}

### GET Foo By ID
GET http://localhost:8080/foos/20000000-0000-0000-0000-000000000001
Accept: application/json

> {%
    if (response.status !== 200) {
        throw new Error(`Expected status 200 but got ${response.status}`);
    }
%}

### Create Foo
POST localhost:8080/foos
Content-Type: application/json

{
  "label": "foo_created",
  "secret": "secret_created"
}

> {%
    if (response.status !== 201) {
        throw new Error(`Expected status 200 but got ${response.status}`);
    }
    const id = response.body.id;
    client.global.set("fooId", id);
%}

### Update Foo
PUT localhost:8080/foos/{{fooId}}
Content-Type: application/json

{
  "label": "foo_updated",
  "secret": "secret_updated"
}

> {%
    if (response.status !== 204) {
        throw new Error(`Expected status 200 but got ${response.status}`);
    }
%}

### Delete Foo
DELETE http://localhost:8080/foos/{{fooId}}
Accept: application/json

> {%
    if (response.status !== 204) {
        throw new Error(`Expected status 200 but got ${response.status}`);
    }
%}