// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: foo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_foo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Foo) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Foo) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CreateFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFooRequest) Reset() {
	*x = CreateFooRequest{}
	mi := &file_foo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFooRequest) ProtoMessage() {}

func (x *CreateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFooRequest.ProtoReflect.Descriptor instead.
func (*CreateFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFooRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateFooRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateFooRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateFooRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type GetFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFooRequest) Reset() {
	*x = GetFooRequest{}
	mi := &file_foo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFooRequest) ProtoMessage() {}

func (x *GetFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFooRequest.ProtoReflect.Descriptor instead.
func (*GetFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{2}
}

func (x *GetFooRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Value         int32                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFooRequest) Reset() {
	*x = UpdateFooRequest{}
	mi := &file_foo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFooRequest) ProtoMessage() {}

func (x *UpdateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFooRequest.ProtoReflect.Descriptor instead.
func (*UpdateFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFooRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFooRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateFooRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UpdateFooRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UpdateFooRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type DeleteFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFooRequest) Reset() {
	*x = DeleteFooRequest{}
	mi := &file_foo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooRequest) ProtoMessage() {}

func (x *DeleteFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooRequest.ProtoReflect.Descriptor instead.
func (*DeleteFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFooRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FooResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           *Foo                   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FooResponse) Reset() {
	*x = FooResponse{}
	mi := &file_foo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FooResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooResponse) ProtoMessage() {}

func (x *FooResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FooResponse.ProtoReflect.Descriptor instead.
func (*FooResponse) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{5}
}

func (x *FooResponse) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

// Requête de liste
type ListFoosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoosRequest) Reset() {
	*x = ListFoosRequest{}
	mi := &file_foo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoosRequest) ProtoMessage() {}

func (x *ListFoosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoosRequest.ProtoReflect.Descriptor instead.
func (*ListFoosRequest) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{6}
}

func (x *ListFoosRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListFoosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListFoosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foos          []*Foo                 `protobuf:"bytes,1,rep,name=foos,proto3" json:"foos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoosResponse) Reset() {
	*x = ListFoosResponse{}
	mi := &file_foo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoosResponse) ProtoMessage() {}

func (x *ListFoosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoosResponse.ProtoReflect.Descriptor instead.
func (*ListFoosResponse) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{7}
}

func (x *ListFoosResponse) GetFoos() []*Foo {
	if x != nil {
		return x.Foos
	}
	return nil
}

type DeleteFooResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFooResponse) Reset() {
	*x = DeleteFooResponse{}
	mi := &file_foo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFooResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooResponse) ProtoMessage() {}

func (x *DeleteFooResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooResponse.ProtoReflect.Descriptor instead.
func (*DeleteFooResponse) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFooResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_foo_proto protoreflect.FileDescriptor

const file_foo_proto_rawDesc = "" +
	"\n" +
	"\tfoo.proto\x12\x05proto\"Y\n" +
	"\x03Foo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\"n\n" +
	"\x10CreateFooRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\"\x1f\n" +
	"\rGetFooRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"~\n" +
	"\x10UpdateFooRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x02R\x06weight\"\"\n" +
	"\x10DeleteFooRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\vFooResponse\x12\x1c\n" +
	"\x03foo\x18\x01 \x01(\v2\n" +
	".proto.FooR\x03foo\"?\n" +
	"\x0fListFoosRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"2\n" +
	"\x10ListFoosResponse\x12\x1e\n" +
	"\x04foos\x18\x01 \x03(\v2\n" +
	".proto.FooR\x04foos\"-\n" +
	"\x11DeleteFooResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa1\x02\n" +
	"\n" +
	"FooService\x125\n" +
	"\x06Create\x12\x17.proto.CreateFooRequest\x1a\x12.proto.FooResponse\x12/\n" +
	"\x03Get\x12\x14.proto.GetFooRequest\x1a\x12.proto.FooResponse\x125\n" +
	"\x06Update\x12\x17.proto.UpdateFooRequest\x1a\x12.proto.FooResponse\x12;\n" +
	"\x06Delete\x12\x17.proto.DeleteFooRequest\x1a\x18.proto.DeleteFooResponse\x127\n" +
	"\x04List\x12\x16.proto.ListFoosRequest\x1a\x17.proto.ListFoosResponseB\x18Z\x16astigo/pkg/proto;protob\x06proto3"

var (
	file_foo_proto_rawDescOnce sync.Once
	file_foo_proto_rawDescData []byte
)

func file_foo_proto_rawDescGZIP() []byte {
	file_foo_proto_rawDescOnce.Do(func() {
		file_foo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foo_proto_rawDesc), len(file_foo_proto_rawDesc)))
	})
	return file_foo_proto_rawDescData
}

var file_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_foo_proto_goTypes = []any{
	(*Foo)(nil),               // 0: proto.Foo
	(*CreateFooRequest)(nil),  // 1: proto.CreateFooRequest
	(*GetFooRequest)(nil),     // 2: proto.GetFooRequest
	(*UpdateFooRequest)(nil),  // 3: proto.UpdateFooRequest
	(*DeleteFooRequest)(nil),  // 4: proto.DeleteFooRequest
	(*FooResponse)(nil),       // 5: proto.FooResponse
	(*ListFoosRequest)(nil),   // 6: proto.ListFoosRequest
	(*ListFoosResponse)(nil),  // 7: proto.ListFoosResponse
	(*DeleteFooResponse)(nil), // 8: proto.DeleteFooResponse
}
var file_foo_proto_depIdxs = []int32{
	0, // 0: proto.FooResponse.foo:type_name -> proto.Foo
	0, // 1: proto.ListFoosResponse.foos:type_name -> proto.Foo
	1, // 2: proto.FooService.Create:input_type -> proto.CreateFooRequest
	2, // 3: proto.FooService.Get:input_type -> proto.GetFooRequest
	3, // 4: proto.FooService.Update:input_type -> proto.UpdateFooRequest
	4, // 5: proto.FooService.Delete:input_type -> proto.DeleteFooRequest
	6, // 6: proto.FooService.List:input_type -> proto.ListFoosRequest
	5, // 7: proto.FooService.Create:output_type -> proto.FooResponse
	5, // 8: proto.FooService.Get:output_type -> proto.FooResponse
	5, // 9: proto.FooService.Update:output_type -> proto.FooResponse
	8, // 10: proto.FooService.Delete:output_type -> proto.DeleteFooResponse
	7, // 11: proto.FooService.List:output_type -> proto.ListFoosResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_foo_proto_init() }
func file_foo_proto_init() {
	if File_foo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foo_proto_rawDesc), len(file_foo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foo_proto_goTypes,
		DependencyIndexes: file_foo_proto_depIdxs,
		MessageInfos:      file_foo_proto_msgTypes,
	}.Build()
	File_foo_proto = out.File
	file_foo_proto_goTypes = nil
	file_foo_proto_depIdxs = nil
}
